baseURL = "http://www.with-pockets.boutique"
languageCode = "en-uk"
title = "With Pockets"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = ""
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
googleAnalytics = "UA-46298735-3"

[params]
  logo = "/images/logo.png"
  description ="Everybody deserves great pockets"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "With Pockets Boutique"
  thumbnail = "/images/author.png"
  description = ""

[params.index]
  picture = "/images/author.png"
  title = "Everybody deserves pockets"
  subtitle = ""
  mdtext = '''
 
'''
  alertbar = false

[params.social]
  twitter = "pocketsboutique"
#  instagram = "<username>"

## Main Menu
#[[menu.main]]
#    name = "Toys"
#    weight = 100
#    identifier = "toys"
#    url = "/blog"
